/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeinVault } from "./VeinVault";
export * as factories from "./factories";
export { VeinVault__factory } from "./factories/VeinVault__factory";
