/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VeinVault {
  export type EvaluationStruct = {
    score: BigNumberish;
    verdict: BigNumberish;
    hasError: boolean;
  };

  export type EvaluationStructOutput = [
    score: bigint,
    verdict: bigint,
    hasError: boolean
  ] & { score: bigint; verdict: bigint; hasError: boolean };
}

export interface VeinVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "capsules"
      | "createCapsule"
      | "depositForFees"
      | "getConvictionScore"
      | "getUserCapsules"
      | "triggerUnlockAndEvaluate"
      | "userCapsules"
      | "userEvaluatedCapsules"
      | "userTotalScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CapsuleCreated"
      | "CapsuleRevealed"
      | "InferenceError"
      | "VerdictStored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "capsules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCapsule",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvictionScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerUnlockAndEvaluate",
    values: [
      BigNumberish,
      AddressLike,
      string,
      BytesLike[],
      BytesLike[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userCapsules",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userEvaluatedCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalScore",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "capsules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvictionScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerUnlockAndEvaluate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEvaluatedCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalScore",
    data: BytesLike
  ): Result;
}

export namespace CapsuleCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    unlockTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    owner: string,
    unlockTimestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    owner: string;
    unlockTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsuleRevealedEvent {
  export type InputTuple = [id: BigNumberish, owner: AddressLike];
  export type OutputTuple = [id: bigint, owner: string];
  export interface OutputObject {
    id: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InferenceErrorEvent {
  export type InputTuple = [id: BigNumberish, errorMsg: string];
  export type OutputTuple = [id: bigint, errorMsg: string];
  export interface OutputObject {
    id: bigint;
    errorMsg: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictStoredEvent {
  export type InputTuple = [
    id: BigNumberish,
    verdict: BigNumberish,
    score: BigNumberish
  ];
  export type OutputTuple = [id: bigint, verdict: bigint, score: bigint];
  export interface OutputObject {
    id: bigint;
    verdict: bigint;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeinVault extends BaseContract {
  connect(runner?: ContractRunner | null): VeinVault;
  waitForDeployment(): Promise<this>;

  interface: VeinVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  capsules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        boolean,
        VeinVault.EvaluationStructOutput
      ] & {
        id: bigint;
        owner: string;
        category: string;
        createdAt: bigint;
        unlockTimestamp: bigint;
        encryptedPayloadHash: string;
        isRevealed: boolean;
        evaluation: VeinVault.EvaluationStructOutput;
      }
    ],
    "view"
  >;

  createCapsule: TypedContractMethod<
    [
      category: string,
      unlockTimestamp: BigNumberish,
      encryptedPayloadHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  depositForFees: TypedContractMethod<
    [lockDuration: BigNumberish],
    [void],
    "payable"
  >;

  getConvictionScore: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserCapsules: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  triggerUnlockAndEvaluate: TypedContractMethod<
    [
      capsuleId: BigNumberish,
      executor: AddressLike,
      messagesJson: string,
      encryptedSecrets: BytesLike[],
      secretSignatures: BytesLike[],
      responseFormatData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userCapsules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userEvaluatedCapsules: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  userTotalScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "capsules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        boolean,
        VeinVault.EvaluationStructOutput
      ] & {
        id: bigint;
        owner: string;
        category: string;
        createdAt: bigint;
        unlockTimestamp: bigint;
        encryptedPayloadHash: string;
        isRevealed: boolean;
        evaluation: VeinVault.EvaluationStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCapsule"
  ): TypedContractMethod<
    [
      category: string,
      unlockTimestamp: BigNumberish,
      encryptedPayloadHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositForFees"
  ): TypedContractMethod<[lockDuration: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getConvictionScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCapsules"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "triggerUnlockAndEvaluate"
  ): TypedContractMethod<
    [
      capsuleId: BigNumberish,
      executor: AddressLike,
      messagesJson: string,
      encryptedSecrets: BytesLike[],
      secretSignatures: BytesLike[],
      responseFormatData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userCapsules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userEvaluatedCapsules"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTotalScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "CapsuleCreated"
  ): TypedContractEvent<
    CapsuleCreatedEvent.InputTuple,
    CapsuleCreatedEvent.OutputTuple,
    CapsuleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CapsuleRevealed"
  ): TypedContractEvent<
    CapsuleRevealedEvent.InputTuple,
    CapsuleRevealedEvent.OutputTuple,
    CapsuleRevealedEvent.OutputObject
  >;
  getEvent(
    key: "InferenceError"
  ): TypedContractEvent<
    InferenceErrorEvent.InputTuple,
    InferenceErrorEvent.OutputTuple,
    InferenceErrorEvent.OutputObject
  >;
  getEvent(
    key: "VerdictStored"
  ): TypedContractEvent<
    VerdictStoredEvent.InputTuple,
    VerdictStoredEvent.OutputTuple,
    VerdictStoredEvent.OutputObject
  >;

  filters: {
    "CapsuleCreated(uint256,address,uint256)": TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;
    CapsuleCreated: TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;

    "CapsuleRevealed(uint256,address)": TypedContractEvent<
      CapsuleRevealedEvent.InputTuple,
      CapsuleRevealedEvent.OutputTuple,
      CapsuleRevealedEvent.OutputObject
    >;
    CapsuleRevealed: TypedContractEvent<
      CapsuleRevealedEvent.InputTuple,
      CapsuleRevealedEvent.OutputTuple,
      CapsuleRevealedEvent.OutputObject
    >;

    "InferenceError(uint256,string)": TypedContractEvent<
      InferenceErrorEvent.InputTuple,
      InferenceErrorEvent.OutputTuple,
      InferenceErrorEvent.OutputObject
    >;
    InferenceError: TypedContractEvent<
      InferenceErrorEvent.InputTuple,
      InferenceErrorEvent.OutputTuple,
      InferenceErrorEvent.OutputObject
    >;

    "VerdictStored(uint256,uint8,uint8)": TypedContractEvent<
      VerdictStoredEvent.InputTuple,
      VerdictStoredEvent.OutputTuple,
      VerdictStoredEvent.OutputObject
    >;
    VerdictStored: TypedContractEvent<
      VerdictStoredEvent.InputTuple,
      VerdictStoredEvent.OutputTuple,
      VerdictStoredEvent.OutputObject
    >;
  };
}
